name: CI

# Specify which GitHub events will trigger a CI build
on: push

# Define a single job, build
jobs:

  build:
    
    # Define a strategy
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    # specify the OS the tests run on
    runs-on: ${{ matrix.os }}

    # define the steps the job takes
    steps:

    # First, checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -e .
    
    # Run our tests
    - name: Test with PyTest
      run: |
        pytest --cov=inflammation.models tests/test_models.py